release:
  enabled: true

subPackages:
  - /build

docker:
  defaultTag: latest
  autoTags: [main, latest, next]

docs:
  location: /docs

  aliases:
    /api: https://raw.githubusercontent.com/corejslib/core/main/docs/api.md

  app:
    rpc:
      url: ws://datasets:81/api
