services:
  datasets:
    image: ghcr.io/zerocluster/datasets
    # depends_on:
    #   postgresql:
    #     condition: service_healthy
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1

    command: run

    secrets:
      - { source: datasets_env.yaml, target: /var/local/package/env.yaml }

    networks: [network]

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }
      - { type: volume, source: datasets, target: /var/local/package/data }

    build: .

secrets:
  datasets_env.yaml: { file: env.yaml }

networks:
  network: ~

volumes:
  datasets: ~
