name: Build datasets
on: workflow_dispatch
# schedule:
#   - cron: "0 12 * * *" # every day at 12:00

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: softvisio/datasets
    steps:
      - run: |
          . /etc/profile.d/n.sh
          npm i
          bin/update-datasets.js --build
        shell: bash
        working-directory: /var/local/package
